name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - run: rustc --version
      - name: Run tests
        run: cargo test --verbose
      - name: Clippy
        run: cargo clippy --all -- -D warnings
      - name: Check formatting
        run: cargo fmt -- --check
